### PR TITLE
Home and contact page (+fix in readme)

### PR DESCRIPTION
**Pull request by giannisdaras**
The link for the project site was wrong.  
Fixed.

### CODE REVIEW

**Comment by tdiam** [comment]
Seems good :+1:

**Comment by tdiam** [comment]
Actually, don't forget to mention the changes in the documentation. I'd suggest we split each app documentation to its own file, e.g. `docs/contact/index.md` and then add links to them in `docs/structure.md`.

**Comment by tdiam** [comment]
Ping

**Comment by giannisdaras** [comment]
Sorry for the late reply. Updated the pull request :)

**Pull request merged**
